version: '3.8'
services:
  db:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: bookstore
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: bookstore
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "55432:5432"    # Host 55432 → Container 5432

  adminer:
    image: adminer:latest
    restart: always
    ports:
      - "8081:8080"     # Adminer web UI
    depends_on:
      - db

  backend:
    build: ./backend
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://bookstore:secret@db:5432/bookstore
      SECRET_KEY: mysupersecretkey
      ALGORITHM: HS256
      ACCESS_TOKEN_EXPIRE_MINUTES: 30
    ports:
      - "8000:8000"     # FastAPI

  frontend:
    build: ./frontend
    depends_on:
      - backend
    ports:
      - "8080:80"       # Nginx front-end

volumes:
  db_data: